import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DocAppointment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body
        className={`${rubik.className} antialiased min-h-screen flex flex-col bg-gray-950/90 text-white`}
      >
        <Navbar />
        <main className="flex-grow"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
